### ISSUE TITLE
Disable darkmode

### ISSUE THREAD

**Issue by moisbo** [UTS-eResearch/describo#1]
I think also windows users have darkmode? If I change to LightMode electron is ok. 

![Screen Shot 2020-03-18 at 3 55 04 pm](https://user-images.githubusercontent.com/2850269/76926591-df10fa80-6930-11ea-987e-64d2567f7fc7.png)

**Comment by marcolarosa** [comment]
I've set the background to white so this no longer happens. Will close the ticket for now and we can start a new one to handle dark mode correctly if this becomes a requriement at some later date. Commit 249dcacb0d9474d04900a8339a5334140f5b1fde
