### ISSUE TITLE
Packaging the crate and delivery

### ISSUE THREAD

**Issue by marcolarosa** [UTS-eResearch/describo#18]
* pull in ro-crate.js
* enable exporting the crate capability 
  * [x] use ro-crate to render a html version into the folder
  * [x] export to zip 
  * [x] ask the user where to store it
* add bagit capability for bonus points
   * [x] see: https://tools.ietf.org/id/draft-kunze-bagit-16.html
   * [x] see calcyte code - provided by PT
   * [x] bag the individual files not the zip file
   * [x] always zip out

**Comment by ptsefton** [comment]
Here's the calcyte code: https://code.research.uts.edu.au/eresearch/CalcyteJS/blob/master/lib/bag.js

**Comment by marcolarosa** [comment]
Closing with https://github.com/UTS-eResearch/describo/commit/57f3fbc3f2ea229dd5eb342184b3ba7c8c9a00f4
