### ISSUE TITLE
When adding a description the insertion point moves as the page redraws on save

### ISSUE THREAD

**Issue by ptsefton** [UTS-eResearch/describo#66]

**Comment by marcolarosa** [comment]
I don't understand this. I think you'll need to show me.

**Comment by marcolarosa** [comment]
rethink the save indicator - too obtrusive with html components resizing

**Comment by marcolarosa** [comment]
Ok - the background now flashes green momentarily to indicate it has saved instead of adding a tick to the view which causes the redraw.
